#!/usr/bin/env python3
"""Extract RS41 sensor-boom factory calibration from a radiosonde_auto_rx
*_subframe.bin dump and emit src/sensor_cal.h for RS41ng.

RS41ng erases the factory flash on first programming, so the per-sonde
calibration must be captured with radiosonde_auto_rx BEFORE flashing.

Byte offsets mirror radiosonde_auto_rx/demod/mod/rs41mod.c get_CalData()
(the function at line 553). CRC16-CCITT (poly 0x1021, init 0xFFFF) is
computed over calibytes[2..800] and compared to the LE word at [0..1].
"""

import argparse
import datetime
import struct
import sys
from pathlib import Path

SUBFRAME_LEN = 816  # 51 * 16

# (macro_name, offset, count) — all values are little-endian float32.
TIER1 = [
    ("SENSOR_BOOM_RF1",    61,  1),
    ("SENSOR_BOOM_RF2",    65,  1),
    ("SENSOR_BOOM_CO1",    77,  3),
    ("SENSOR_BOOM_CALT1",  89,  3),
    ("SENSOR_BOOM_CALH0", 117,  1),
    ("SENSOR_BOOM_CO2",   293,  3),
    ("SENSOR_BOOM_CALT2", 305,  3),
]

TIER2 = [
    ("SENSOR_BOOM_CF1",    69,  1),
    ("SENSOR_BOOM_CF2",    73,  1),
    ("SENSOR_BOOM_CALH1", 121,  1),
    ("SENSOR_BOOM_MTXH",  125, 42),
    ("SENSOR_BOOM_CORHP", 678,  3),
    ("SENSOR_BOOM_CORHT", 698, 12),
]


def crc16_ccitt(data: bytes) -> int:
    rem = 0xFFFF
    for byte in data:
        rem ^= byte << 8
        for _ in range(8):
            rem = ((rem << 1) ^ 0x1021) if (rem & 0x8000) else (rem << 1)
            rem &= 0xFFFF
    return rem


def read_floats(buf: bytes, offset: int, count: int):
    return list(struct.unpack_from("<" + "f" * count, buf, offset))


def fmt_macro(name: str, values: list[float]) -> str:
    if len(values) == 1:
        return f"#define {name:22s} {values[0]!r}f"
    body = ", ".join(f"{v!r}f" for v in values)
    return f"#define {name:22s} {{ {body} }}"


def sonde_serial(buf: bytes) -> str:
    # 8-char ASCII serial lives at calfr 0x00 offset 13 (0x0D).
    raw = bytes(b for b in buf[13:21] if 0x20 <= b < 0x7F)
    return raw.decode("ascii", errors="replace").strip() or "(unknown)"


def tier2_all_ff(buf: bytes) -> bool:
    ranges = [(offset, offset + 4 * count) for _, offset, count in TIER2
              if count > 1]  # check the bulk arrays, not the single floats
    return all(all(b == 0xFF for b in buf[lo:hi]) for lo, hi in ranges)


def render_header(buf: bytes, source_path: Path, crc_ok: bool) -> str:
    lines = [
        "// Auto-generated by tools/extract_rs41_cal.py — DO NOT EDIT BY HAND",
        f"// Source:  {source_path.name}",
        f"// Sonde:   {sonde_serial(buf)}",
        f"// Gen:     {datetime.datetime.now().isoformat(timespec='seconds')}",
        f"// CRC16:   {'OK' if crc_ok else 'FAIL (forced)'}",
        "",
        "#ifndef SENSOR_CAL_H",
        "#define SENSOR_CAL_H",
        "",
        "// --- Tier 1 (always required when SENSOR_BOOM_ENABLE) ---",
    ]
    for name, off, n in TIER1:
        lines.append(fmt_macro(name, read_floats(buf, off, n)))
    lines.append("")
    lines.append("// --- Tier 2 (required only when SENSOR_BOOM_RH_MODEL_PHYSICAL) ---")
    for name, off, n in TIER2:
        lines.append(fmt_macro(name, read_floats(buf, off, n)))
    lines.append("")
    lines.append("#endif  // SENSOR_CAL_H")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("subframe_bin", type=Path,
                    help="path to *_subframe.bin from radiosonde_auto_rx")
    default_out = Path(__file__).resolve().parent.parent / "src" / "sensor_cal.h"
    ap.add_argument("-o", "--output", type=Path, default=default_out,
                    help=f"output header path (default: {default_out})")
    ap.add_argument("--stdout", action="store_true",
                    help="write to stdout instead of a file")
    ap.add_argument("--force", action="store_true",
                    help="overwrite existing output and ignore CRC mismatch")
    args = ap.parse_args()

    buf = args.subframe_bin.read_bytes()
    if len(buf) != SUBFRAME_LEN:
        print(f"error: expected {SUBFRAME_LEN}-byte subframe, got {len(buf)}",
              file=sys.stderr)
        return 2

    stored = buf[0] | (buf[1] << 8)
    computed = crc16_ccitt(buf[2:800])
    crc_ok = (stored == computed)
    if not crc_ok:
        msg = f"CRC mismatch: stored=0x{stored:04x} computed=0x{computed:04x}"
        if not args.force:
            print(f"error: {msg} (use --force to emit anyway)", file=sys.stderr)
            return 3
        print(f"warning: {msg} — emitting because --force", file=sys.stderr)

    if tier2_all_ff(buf):
        print("warning: Tier-2 cal bytes are all 0xFF — the sonde likely "
              "never transmitted subframes 0x07–0x11 / 0x2A–0x2E during the "
              "auto_rx capture. Physical RH path will give bad results; "
              "build with SENSOR_BOOM_RH_MODEL_PHYSICAL=false or capture "
              "a longer auto_rx run.", file=sys.stderr)

    rendered = render_header(buf, args.subframe_bin, crc_ok)

    if args.stdout:
        sys.stdout.write(rendered)
        return 0

    if args.output.exists() and not args.force:
        print(f"error: {args.output} exists (use --force to overwrite)",
              file=sys.stderr)
        return 4

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered)
    print(f"wrote {args.output} (sonde {sonde_serial(buf)}, "
          f"CRC {'OK' if crc_ok else 'FAIL'})", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
